[pytest]
testpaths = testcases
pythonpath = .
addopts = -vs --html=report/report.html --self-contained-html
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    create: 新建
    distribute: 分发
    stash: 暂存
    submit: 提交
    generate_sub_order: 生成子订单
    fee_add: 录入费用

log_cli = True
log_cli_level = INFO
log_file_level = INFO

filterwarnings =
    ignore::pytest.PytestUnknownMarkWarning
